fragment PoliticFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		blocks
		value
		links
	}
	content {
		value
		links
	}
	image {
		...ImageFragment
	}
	slug
}
