fragment PoliticFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		blocks
		value
		links
	}
	content {
		value
		links
		blocks {
			... on ButtonBlockRecord {
				__typename
				id
				text
				url
			}
			... on ImageBlockRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
		}
	}
	image {
		...ImageFragment
	}
	slug
	_createdAt
	_publishedAt
}
