fragment PoliticLightFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		blocks
		value
		links
	}
	image {
		...ImageFragment
	}
	slug
	_publishedAt
	_createdAt
}
