fragment PoliticFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		blocks
		value
		links
	}
	content {
		value
		links
		blocks {
			__typename
			... on ButtonBlockRecord {
				id
				text
				url
			}
			... on ImageBlockRecord {
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on VideoBlockRecord {
				id
				video {
					...ExternalVideoFragment
				}
			}
		}
	}
	image {
		...ImageFragment
	}
	slug
	_createdAt
	_publishedAt
}
