query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		id
		slug
		title
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

fragment AboutLightFragment on AboutRecord {
	id
	slug
	title
}

fragment AboutFragment on AboutRecord {
	id
	slug
	title
	intro {
		blocks
		links
		value
	}
	content {
		blocks {
			__typename
			... on PeopleCollectionBlockRecord {
				id
				people {
					...StaffFragment
				}
			}
			... on ButtonBlockRecord {
				id
				text
				url
			}
		}
		links
		value
	}
}
