query AllAbouts {
	allAbouts {
		id
		slug
		title
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		id
		slug
		title
		intro {
			blocks
			links
			value
		}
		content {
			blocks {
				... on PeopleCollectionBlockRecord {
					__typename
					id
					people {
						...StaffFragment
					}
				}
			}
			links
			value
		}
	}
}
