query Contact {
	contactPage {
		...ContactPageFragment
	}
}

fragment ContactPageFragment on ContactPageRecord {
	id
	title
	intro {
		blocks
		links
		value
	}
	slug
	staff {
		...StaffFragment
	}
}
