query MemberPage {
	memberPage {
		...MemberPageFragment
	}
	allMemberLevels(orderBy: level_ASC) {
		...MemberLevelFragment
	}
}

fragment MemberPageFragment on MemberPageRecord {
	id
	title
	intro {
		blocks
		links
		value
	}
	content {
		blocks
		links
		value
	}
	slug
}

query AllApprovedMembers($first: IntType = 100, $skip: IntType = 0) {
	allMembers(first: $first, skip: $skip, orderBy: organization_ASC, filter: { approved: { eq: true } }) {
		...MemberFragment
	}
	_allMembersMeta(filter: { approved: { eq: true } }) {
		count
	}
}

fragment MemberFragment on MemberRecord {
	id
	organization
	organizationNo
	contact
	email
	invoiceAddress
	level {
		...MemberLevelFragment
	}
	approved
}

fragment MemberLevelFragment on MemberLevelRecord {
	id
	level
	turnoverMax
	turnoverMin
}
