query MemberPage {
	memberPage {
		...MemberPageFragment
	}
	allMemberLevels(orderBy: level_ASC) {
		...MemberLevelFragment
	}
}

fragment MemberPageFragment on MemberPageRecord {
	id
	title
	intro {
		blocks
		links
		value
	}
	content {
		blocks
		links
		value
	}
	slug
}

query AllApprovedMembers {
	allMembers(orderBy: organization_ASC, filter: { approved: { eq: true } }) {
		...MemberFragment
	}
}

fragment MemberFragment on MemberRecord {
	id
	organization
	organizationNo
	contact
	email
	invoiceAddress
	level {
		...MemberLevelFragment
	}
	approved
}
