query AllPolitic($first: IntType = 100, $skip: IntType = 0) {
	allPolitics(first: $first, skip: $skip) {
		id
		title
		slug
		category {
			id
			title
			slug
		}
	}
	_allPoliticsMeta {
		count
	}
}

query Politic($slug: String!) {
	politic(filter: { slug: { eq: $slug } }) {
		...PoliticFragment
	}
}

query PoliticCategory($slug: String!) {
	politicCategory(filter: { slug: { eq: $slug } }) {
		...PoliticCategoryFragment
	}
}

query AllPoliticByCategory($id: ItemId!, $first: IntType = 1, $skip: IntType = 0) {
	allPolitics(first: $first, skip: $skip, filter: { category: { eq: $id } }) {
		...PoliticFragment
	}
	_allPoliticsMeta(filter: { category: { eq: $id } }) {
		count
	}
}

query AllPoliticCategories($first: IntType = 100, $skip: IntType = 0) {
	allPoliticCategories(first: $first, skip: $skip) {
		...PoliticCategoryFragment
	}
	_allPoliticCategoriesMeta {
		count
	}
}

fragment PoliticCategoryFragment on PoliticCategoryRecord {
	id
	title
	titlePlural
	slug
	position
}

fragment PoliticFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		__typename
		blocks
		value
		value
	}
	content {
		value
		links
		blocks {
			__typename
			... on ButtonBlockRecord {
				id
				text
				url
			}
			... on ImageBlockRecord {
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on VideoBlockRecord {
				id
				video {
					...ExternalVideoFragment
				}
			}
		}
	}
	image {
		...ImageFragment
	}
	slug
	_createdAt
	_publishedAt
}

fragment PoliticLightFragment on PoliticRecord {
	id
	title
	category {
		...PoliticCategoryFragment
	}
	intro {
		__typename
		blocks
		value
		links
	}
	image {
		...ImageFragment
	}
	slug
	_publishedAt
	_createdAt
}
