query AllPolitic($first: IntType = 100, $skip: IntType = 0) {
	allPolitics(first: $first, skip: $skip) {
		id
		title
		slug
		category {
			id
			title
			slug
		}
	}
	_allPoliticsMeta {
		count
	}
}

query Politic($slug: String!) {
	politic(filter: { slug: { eq: $slug } }) {
		...PoliticFragment
	}
}

query PoliticCategory($slug: String!, $id: ItemId!) {
	politicCategory(filter: { OR: [{ slug: { eq: $slug } }, { id: { eq: $id } }] }) {
		...PoliticCategoryFragment
	}
}

query AllPoliticByCategory($id: ItemId!, $first: IntType = 1, $skip: IntType = 0) {
	allPolitics(first: $first, skip: $skip, filter: { category: { eq: $id } }) {
		...PoliticFragment
	}
	_allPoliticsMeta(filter: { category: { eq: $id } }) {
		count
	}
}

query AllPoliticCategories($first: IntType = 100, $skip: IntType = 0) {
	allPoliticCategories(first: $first, skip: $skip) {
		...PoliticCategoryFragment
	}
	_allPoliticCategoriesMeta {
		count
	}
}
