query AllResources($first: IntType = 100, $skip: IntType = 0) {
	allResources(first: $first, skip: $skip) {
		id
		title
		author
		publisher
		subtitle
		category {
			id
			title
		}
		theme {
			id
			title
		}
		summary {
			links
			value
		}
		link {
			... on ExternalLinkRecord {
				id
				title
				url
			}
		}
		_publishedAt
	}
	_allResourcesMeta {
		count
	}
	allResourceCategories {
		id
		title
	}
	_allResourceCategoriesMeta {
		count
	}
}
