query Start {
	start {
		id
		content {
			__typename
			... on StartPoliticBlockRecord {
				id
				record {
					... on PoliticRecord {
						...PoliticLightFragment
					}
				}
				layout
			}
			... on NewsletterBlockRecord {
				id
				title
			}
			... on TextBlockRecord {
				id

				texts {
					id
					headline
					text
					image {
						...ImageFragment
					}
					link {
						... on InternalLinkRecord {
							__typename
							id
							title
							link {
								__typename
								... on PoliticRecord {
									...PoliticLightFragment
								}
								... on AboutRecord {
									...AboutLightFragment
								}
								... on ContactPageRecord {
									...ContactPageFragment
								}
								... on MemberPageRecord {
									...MemberPageFragment
								}
							}
						}
						... on ExternalLinkRecord {
							__typename
							id
							title
							url
						}
					}
				}
			}
		}
		smallColumn {
			__typename
			... on NoticeBlockRecord {
				id
				headline
				text
				link {
					... on InternalLinkRecord {
						__typename
						id
						title
						link {
							__typename
							... on PoliticRecord {
								...PoliticLightFragment
							}
							... on AboutRecord {
								...AboutLightFragment
							}
							... on ContactPageRecord {
								...ContactPageFragment
							}
							... on MemberPageRecord {
								...MemberPageFragment
							}
						}
					}
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
				}
			}
		}
	}
}
