query Start {
	start {
		id
		content {
			__typename
			... on StartPoliticBlockRecord {
				id
				record {
					... on PoliticRecord {
						...PoliticLightFragment
					}
				}
				layout
			}
		}
	}
}
