query Start {
	start {
		id
		content {
			__typename
			... on StartPoliticBlockRecord {
				id
				record {
					... on PoliticRecord {
						...PoliticLightFragment
					}
				}
				layout
			}
			... on TextBlockRecord {
				id
				texts {
					id
					headline
					text
					link {
						... on InternalLinkRecord {
							__typename
							id
							title
							link {
								__typename
								... on PoliticRecord {
									...PoliticLightFragment
								}
								... on AboutRecord {
									...AboutLightFragment
								}
								... on ContactPageRecord {
									...ContactPageFragment
								}
								... on MemberPageRecord {
									...MemberPageFragment
								}
							}
						}
						... on ExternalLinkRecord {
							__typename
							id
							title
							url
						}
					}
				}
			}
		}
	}
}
