query AllTools($first: IntType = 100, $skip: IntType = 0) {
	allTools(first: $first, skip: $skip) {
		id
		title
		slug
		image {
			...ImageFragment
		}
	}
	_allToolsMeta {
		count
	}
}

query Tool($slug: String!) {
	tool(filter: { slug: { eq: $slug } }) {
		...ToolFragment
	}
}

fragment ToolFragment on ToolRecord {
	id
	title
	slug
	image {
		...ImageFragment
	}
	intro {
		blocks
		value
		links
	}
	content {
		blocks {
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
		}
		value
		links
	}
}
