export { default as StartPoliticBlock } from './StartPoliticBlock'
export { default as PeopleCollectionBlock } from './PeopleCollectionBlock'
export { default as TextBlock } from './TextBlock'
export { default as NoticeBlock } from './NoticeBlock'
export { default as NewsletterBlock } from './NewsletterBlock'